# tryExceptTest1.py
try :
	num = int(input('Please type a number:'))
except ValueError:
	print('Value Error.Please enter a number!')